version : "3"

services:
   app:
     build: .
     command: [sh, -c, "cd /usr/app && npx prisma migrate && npm run dev "]
     ports:
       - "3000:3000"
     volumes:
       - ".:/usr/app"

   db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - "3308:1433"
    working_dir: /usr/app 
    environment:
      ACCEPT_EULA: Y
