version: '3.3'

services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - '3308:1433'
    working_dir: /usr/app
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Devworld1231@!
  app:
    container_name: nodejs
    build: .
    command: [sh, -c, 'cd /usr/app && npx prisma migrate && npm run dev ']
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/app'
    depends_on:
      - db
